### ISSUE TITLE
API compatibility with chokidar

### ISSUE THREAD

**Issue by janraasch** [efacilitation/watch-network#7]
Hi,

I really like this project. I may be totally off track here, but do you think it would be at all possible to isolate the *base* (watching files over the network) of this in a module with an API compatible with [chokidar](https://www.npmjs.com/package/chokidar)  (or maybe a common subset of the API), e.g. this like

```js
watcher
  .on('add', function(path) { log('File', path, 'has been added'); })
  .on('change', function(path) { log('File', path, 'has been changed'); })
  .on('unlink', function(path) { log('File', path, 'has been removed'); })
  .on('addDir', function(path) { log('Directory', path, 'has been added'); })
  .on('unlinkDir', function(path) { log('Directory', path, 'has been removed'); })
  .on('error', function(error) { log('Error happened', error); })
  .on('ready', function() { log('Initial scan complete. Ready for changes.'); })
  .on('raw', function(event, path, details) { log('Raw event info:', event, path, details); })
 

watcher.on('change', function(path, stats) {
  if (stats) console.log('File', path, 'changed size to', stats.size);
});
```

If so, that module could be integrated (as simply another file watching implementation) into `chokidar` and hence be easily used in modules like `browserify`, `webpack` and all the others that rely on `chokidar`. (See https://www.npmjs.com/browse/depended/chokidar)

What do you think?

**Comment by alexlawrence** [comment]
Sounds interesting. 

However, if I understand this correctly, this would either require chokidar to have a kind of plugin mechanism where the underlying implementation could be switched or all modules which currently use chokidar to instead use a common interface which chokidar and watch-network would implement. Correct @janraasch ?

**Comment by janraasch** [comment]
> this would either require chokidar to have a kind of plugin mechanism where the underlying implementation could be switched

Exactly, actually `chokidar` is already pretty flexible. It uses `FSEvents` on Mac OS X and node's own `fs` module otherwise. They also do a great job normalizing otherwise weird events. So I think it should not be to hard to integrate a `watch-network`-like implementation.

So a goal could be to write a module like 

- https://github.com/paulmillr/chokidar/blob/master/lib/fsevents-handler.js or
- https://github.com/paulmillr/chokidar/blob/master/lib/nodefs-handler.js

e.g. `listen-handler.js` to be used inside `chokidar`.

I think this could be super helpful for people using VMs for development.

**Comment by alexlawrence** [comment]
> I think this could be super helpful for people using VMs for development.

I agree.

> e.g. listen-handler.js to be used inside chokidar (i.e. https://github.com/paulmillr/chokidar/blob/master/index.js).

As a side note: I´m not sure whether I would do this from an architetural point of view. As far as I can see, chokidar abstracts OS differences away. Introducing a "listen-handler" would be more like choosing a specific scenario (file changes of the network).

Anyway: I like the idea and we would probably switch to chokidar if such a listener would exist. However, we won´t be re-writing this module and I see it more as an issue which should be placed in the chokidar project, especially since a pull request would also belong there.

@janraasch If you plan on writing a listen based handler for chokidar don´t hesitate to ask for support if you need it. If chokidar will get such a handler we will consider marking this module is deprecated.
